#!/usr/bin/env ruby
#^syntax detection

site 'https://supermarket.chef.io/api/v1'

cookbook 'chef-client'

# system core
cookbook 'zsh'

# aws
cookbook 'aws'
cookbook 'awscli'
cookbook 'aws-sdk'
cookbook 'aws-rds'
cookbook 'aws-vpc-nat-instance'
cookbook 'aws-ec2-assign-elastic-ip'

# ruby
cookbook 'rbenv'
# cookbook 'rbenv-gemset'
cookbook 'rbenv-bootstrap'

# webserver
cookbook 'nginx'

# kafka, etc
cookbook 'apache_kafka'
cookbook 'zookeeper'

# search
cookbook 'elasticsearch'

# data
cookbook 'postgresql'
cookbook 'redis'

# monitoring
cookbook 'newrelic'

#custom

